import { useGetSharedReport } from "@workspace/api-client-react"
import { useParams } from "wouter"
import { ShieldHalf, FileText } from "lucide-react"
import { format } from "date-fns"

/**
 * Public, unauthenticated report view rendered outside the app shell — the
 * destination of a shareable report link.
 */
export default function SharedReport() {
  const { token } = useParams()
  const { data: report } = useGetSharedReport(token || "", {
    query: { enabled: !!token, queryKey: ["shared-report", token] },
  })

  return (
    <div className="min-h-[100dvh]">
      <header className="glass sticky top-0 z-10 flex h-16 items-center gap-3 border-b border-border/60 px-6">
        <div className="ring-glow flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-fuchsia-500 text-white">
          <ShieldHalf className="h-5 w-5" />
        </div>
        <div className="leading-tight">
          <div className="font-display text-lg font-bold"><span className="text-gradient">PentAI</span></div>
          <div className="text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Shared report</div>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-10">
        {!report ? (
          <p className="text-muted-foreground">Loading report…</p>
        ) : (
          <div className="card-premium p-8">
            <div className="mb-6 flex items-center justify-between border-b border-border/60 pb-4">
              <div>
                <h1 className="flex items-center gap-2 font-display text-2xl font-bold">
                  <FileText className="h-6 w-6 text-primary" />
                  Assessment report
                </h1>
                <p className="mt-1 text-sm text-muted-foreground">
                  {report.targetHost} · generated {format(new Date(report.generatedAt), "yyyy-MM-dd HH:mm")} UTC
                </p>
              </div>
              <span className="rounded-full bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">
                {report.findingCount} findings
              </span>
            </div>
            <pre className="whitespace-pre-wrap break-words font-mono text-sm leading-relaxed text-foreground">
              {report.summary || "No summary available."}
            </pre>
          </div>
        )}
        <p className="mt-6 text-center text-xs text-muted-foreground">
          Generated by PentAI — autonomous, authorization-first web pentesting.
        </p>
      </main>
    </div>
  )
}
